name: "Godot Export CI"

# Whenever a push is made to the master branch then run the job.
on: 
  push:
    branches:
      - main

jobs:
  export_game:
    # Always use ubuntu-latest for this action.
    runs-on: ubuntu-latest
    name: Godot Export
    steps:
      # Always include the checkout step so that 
      # the project is available for Godot to export.
    - name: checkout
      uses: actions/checkout@v2.3.1
      # Ensure that you get the entire project history.
      with:
        fetch-depth: 0
    - name: export game
      # Use latest version.
      uses: firebelley/godot-export@v3.0.0
      with:
        # Define all the required inputs.
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.4/Godot_v3.4-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.4/Godot_v3.4-stable_export_templates.tpz
        relative_project_path: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
